deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: V4JccOGM25b8LpUSJWluMXd2WuMaWv3hQfjHvLOUmYPlXl12jJ4HxZYFM9cvsWuXidepGQB8x4LMhLtdV+Vjh5tfA38lOeT8Dmh+9sRCXom41QJLlQmZgntJECnrVwIARBfNKGptVpPZLIg4gQD9Fr2lIm9XEWv+KdPkrlbXfT0qh7uIjtqmaRbVSJXxCfj++EsHHVAs8bWI55QHx8X/EC2B602K7pQcxYcipyVBYtDLrKx6m4JPVcdZmghajIOzi2Z++72B6klBLa3iU4nMtH+VYRkgtUryHVXuH7vQrziLukE+5t2qovMsd6GyezpbYHjKvxRgoShcRFmJOw9dPOIwyDnOFDHr9c8td9KRRKuQCS2w8x2gVJnaEufOZUA2x4g9ptHbqMFWTkttiPoHCATt+15SCtsKVIoqzLJm7NFsgIZOsuABzU+6xzPIpkwnCfoqHcbLY1FM2Q8ViS+A055Ml+B/OZ+OUpNPl4Ss5VNmN65eZu1jcSSeEPxif9QNiUUNIoRYkqsOjCi3i1x5d0sf3Nftpyet1oqJWo9AEdGAN3Ryg/04Jj2hthO9dBGp9V32mePNPskXjmdYkhjEm3Fp2lVhz0E79gH9aSW+Z4lqcQs8g8beMr+XHHrB113I1H3kJ4YylyRa38kLNsfqikr1zTy0WlXnNSYo6LBbUZ8=
  secret_access_key:
    secure: upa1/9UVPbZvgFLmc/5i3rXDvowzM2yLf9TV4x2dpcSohPQ2lpggpycZAAmbLVtBWaZR8MupAJZuzgoemGJ7kjLaXoAAyzyqXE+Jozw6wiFyRncr29uIF8Iu0cA2FnwL8PJ2J3OxjFnztiVXWrOAx5eSkCBnTaHz4UMFzYzYvWQ6lyZ2sqX3yTHATthJV/Mvv+jSLzY28u1AxoLpOID6UkcHOrZYTS1PUY2vvsJGQ8CPnBqLVmq/HKKpDmkh7qrOzf/r9gUtmFUfYCx4bl8Vknmwnk/wiLp6QgZ5DH51VcpRCzzrWDgIaji7QSwj5P2qkDUhjFi/3lvYA+P8ijNcqoT0C1Ih6M4WPiJ8GjVA2YHS1RKh9/2bnEZQbqWSCbfGal+65/ImHnCSt3f6KdlbJ9W/9b8J3SLN6XQ1eYTVG8HoENLS8CQEz03wgtkqwWDk9PWt/FQYyWiCeYMSoOflT5qx7kZfCKlOOwOdOaOVAT7ZF90sO4J89BM6fW32HUO9F/2mie8gxqJl86mvWK8y67m8GwbeAljHEkOqDmkktpnFeuF6wTyap8k74GJ5J/CCcNINKkLE/Nq1uSjtuxhg4NrJbL4aURddLR+QcbEJIeCxoZOELAoTRvR3ZOJSILmACa4ozzVYh9qKMQ5GB/1lyWcWZq8MIOr4W5n1CJgntRg=
  region: us-east-2
  app: CODA
  env: Coda-env
  bucket_name: elasticbeanstalk-us-east-2-499364046553
  on:
    repo: PhytosphereResearch/CODA-server
  skip_cleanup: true
